apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db_setter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: backend-pod
      labels:
        app: db_setter
    spec:
      containers:
        - image: demiproger/pdris_task_1_setter
          name: pdris_task_1_setter_container
          ports:
            - containerPort: 8080
              name: setter-port
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: db_setter