apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pv-claim
      containers:
        - image: mongo:latest
          name: db
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 27017
              name: db-port
          volumeMounts:
            - name: mongodb-storage
              mountPath: /var/lib/mongo/data
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  ports:
    - port: 27017
  selector:
    app: db
