apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db-setter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: bd-setter-pod
      labels:
        app: db-setter
    spec:
      containers:
        - image: demiproger/pdris_task_1_setter
          name: pdris-task-1-setter-container
          ports:
            - containerPort: 8081
              name: setter-port
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: db-setter
